// docs/src/components/examples/XyzTransition/Switch.vue
<template>
	<div class="example-wrap flex-col">
		<XyzTransition appear mode="out-in">
			<div
				class="square"
				xyz="fade left-100%"
				v-if="customData.shapes[customData.shapeIndex] === 'square'"
				key="square"
			></div>
			<div
				class="circle"
				xyz="fade up-100%"
				v-if="customData.shapes[customData.shapeIndex] === 'circle'"
				key="circle"
			></div>
			<div
				class="triangle"
				xyz="fade right-100%"
				v-if="customData.shapes[customData.shapeIndex] === 'triangle'"
				key="triangle"
			></div>
		</XyzTransition>
		<button class="example-button mt-l" @click="changeShape">Click to switch</button>
	</div>
</template>

<script>
import ExampleMixin from '../ExampleMixin'

export default {
	mixins: [ExampleMixin],
	data() {
		return {
			customData: {
				shapeIndex: 0,
				shapes: ['square', 'circle', 'triangle'],
			},
		}
	},
	methods: {
		changeShape() {
			this.customData.shapeIndex++
			if (this.customData.shapeIndex === this.customData.shapes.length) {
				this.customData.shapeIndex = 0
			}
		},
	},
}
</script>

// examples/react/src/examples/XyzTransition/Switch.jsx
import React, { useState } from 'react'
import { XyzTransition } from '@animxyz/react'

export default function Example() {
	const shapes = ['square', 'circle', 'triangle']
	const [shapeIndex, setShapeIndex] = useState(0)

	function changeShape() {
		let newShapeIndex = shapeIndex + 1
		if (newShapeIndex === shapes.length) {
			newShapeIndex = 0
		}
		setShapeIndex(newShapeIndex)
	}

	return (
		<div className="example-wrap flex-col">
			<XyzTransition appear mode="out-in">
				{shapes[shapeIndex] === 'square' && <div className="square" data-xyz="fade left-100%" key="square" />}
				{shapes[shapeIndex] === 'circle' && <div className="circle" data-xyz="fade up-100%" key="circle" />}
				{shapes[shapeIndex] === 'triangle' && <div className="triangle" data-xyz="fade right-100%" key="triangle" />}
			</XyzTransition>
			<button className="example-button mt-l" onClick={changeShape}>
				Click to switch
			</button>
		</div>
	)
}
