// site/src/components/vue/examples/XyzTransition/Toggle.vue
<template>
  <div class="example-wrap flex-col">
    <XyzTransition appear data-xyz="fade rotate-right ease-out-back">
      <div class="square" v-if="customData.buttonToggled"></div>
    </XyzTransition>
    <button class="example-button mt-l" @click="customData.buttonToggled = !customData.buttonToggled">
      Click to toggle
    </button>
  </div>
</template>

<script>
import ExampleMixin from '~/components/vue/examples/exampleMixin'

export default {
  mixins: [ExampleMixin],
  data() {
    return {
      customData: {
        buttonToggled: true,
      },
    }
  },
}
</script>

// examples/react/src/examples/XyzTransition/Toggle.jsx
import React, { useState } from 'react'
import { XyzTransition } from '@animxyz/react'

export default function Example() {
	const [buttonToggled, setButtonToggled] = useState(true)

	return (
		<div className="example-wrap flex-col">
			<XyzTransition appear xyz="fade rotate-right ease-out-back">
				{buttonToggled && <div className="square" />}
			</XyzTransition>
			<button className="example-button mt-l" onClick={() => setButtonToggled(!buttonToggled)}>
				Click to toggle
			</button>
		</div>
	)
}
