// examples/vue3/src/examples/XyzTransitionGroup/Nested.vue
<template>
	<div class="example-wrap flex-col">
		<XyzTransitionGroup
			appear
			duration="auto"
			class="example-grid"
			xyz="fade flip-left origin-left duration-3 appear-stagger"
		>
			<div class="item-block" v-for="index in numElements" :key="index">
				<div class="square xyz-nested" xyz="fade small stagger" v-for="subIndex in 4" :key="subIndex"></div>
			</div>
		</XyzTransitionGroup>
		<div class="flex-row">
			<button class="example-button mt-l" @click="addElement">Add Element</button>
			<button class="example-button mt-l" @click="removeElement">Remove Element</button>
		</div>
	</div>
</template>

<script>
export default {
	data() {
		return {
			numElements: 3,
		}
	},
	methods: {
		addElement() {
			this.numElements += 1
		},
		removeElement() {
			if (this.numElements > 0) {
				this.numElements -= 1
			}
		},
	},
}
</script>

// examples/react/src/examples/XyzTransitionGroup/Nested.jsx
import React, { useState } from 'react'
import { XyzTransitionGroup } from '@animxyz/react'

export default function Example() {
	const [numElements, setNumElements] = useState(3)

	function addElement() {
		setNumElements((oldNumElements) => oldNumElements + 1)
	}

	function removeElement() {
		setNumElements((oldNumElements) => {
			if (oldNumElements > 0) {
				return oldNumElements - 1
			}
			return oldNumElements
		})
	}

	return (
		<div className="example-wrap flex-col">
			<XyzTransitionGroup
				appear
				duration="auto"
				className="example-grid"
				xyz="fade flip-left origin-left duration-3 appear-stagger"
			>
				{[...Array(numElements)].map((_, index) => (
					<div className="item-block" key={index}>
						{[...Array(4)].map((_, subIndex) => (
							<div className="square xyz-nested" data-xyz="fade small stagger" key={subIndex} />
						))}
					</div>
				))}
			</XyzTransitionGroup>
			<div className="flex-row">
				<button className="example-button mt-l" onClick={addElement}>
					Add Element
				</button>
				<button className="example-button mt-l" onClick={removeElement}>
					Remove Element
				</button>
			</div>
		</div>
	)
}
