// examples/react/src/examples/XyzTransition/Toggle.jsx
import React, { useState } from 'react'
import { XyzTransition } from '@animxyz/react'

export default function Example() {
	const [buttonToggled, setButtonToggled] = useState(true)

	return (
		<div className="example-wrap flex-col">
			<XyzTransition appear xyz="fade rotate-right ease-out-back">
				{buttonToggled && <div className="square" />}
			</XyzTransition>
			<button className="example-button mt-l" onClick={() => setButtonToggled(!buttonToggled)}>
				Click to toggle
			</button>
		</div>
	)
}

// examples/vue/src/examples/XyzTransition/Toggle.vue
<template>
	<div class="example-wrap flex-col">
		<XyzTransition appear data-xyz="fade rotate-right ease-out-back">
			<div class="square" v-if="buttonToggled"></div>
		</XyzTransition>
		<button class="example-button mt-l" @click="buttonToggled = !buttonToggled">Click to toggle</button>
	</div>
</template>

<script>
export default {
	data() {
		return {
			buttonToggled: true,
		}
	},
}
</script>
