// examples/react/src/examples/XyzTransitionGroup/AppearVisible.jsx
import React from 'react'
import { XyzTransitionGroup } from '@animxyz/react'
import './AppearVisible.scoped.scss'

export default function Example() {
	return (
		<div className="example-wrap">
			<div className="scroll-wrap">
				<XyzTransitionGroup appearVisible class="example-grid" xyz="delay-2 fade small rotate-right">
					{[...Array(200)].map((_, index) => (
						<div className="square" key={index} />
					))}
				</XyzTransitionGroup>
			</div>
		</div>
	)
}

// examples/vue/src/examples/XyzTransitionGroup/AppearVisible.vue
<template>
	<div class="example-wrap">
		<div class="scroll-wrap">
			<XyzTransitionGroup appear-visible class="example-grid" xyz="delay-2 fade small rotate-right">
				<div class="square" v-for="index in 200" :key="index"></div>
			</XyzTransitionGroup>
		</div>
	</div>
</template>

<script>
export default {}
</script>

<style lang="scss" scoped>
.scroll-wrap {
	overflow-y: auto;
	max-height: 28rem;
}

.example-grid {
	gap: $sp-xxs;
}
</style>
